### ISSUE TITLE
User not authorized to connect in GLPI

### ISSUE THREAD

**Issue by ropelletier** [edgardmessias/glpi-singlesignon#19]
Newly install plugin. Tried before manually adding user, though Automatically add user from external authentication is Yes. Still getting the error even after manually adding the user. 

I know my Google settings are correct, what else should I look for?

Should I have anything in Scope?

**Comment by adcor44** [comment]
could this problem be solved?

**Comment by edgardmessias** [comment]
Could you update to latest release and run "Test" from config page?

https://github.com/edgardmessias/glpi-singlesignon/releases/tag/v1.3.3

**Comment by edgardmessias** [comment]
Closed in favor of #26

**Comment by surendra5254** [comment]
I picked the sso single plugin from the repo. I configured google ticket and I was able to authenticate with google server but users are not automatically provisioning in the GLPI. I am getting "User is not authorized to connect in GLPI" error page. Let me know how to provision the user automatically instead of creating it manually for sso,

**Comment by nguyencongvan** [comment]
I also see this problem, would you help me?

**Comment by leo-333** [comment]
Could you solve the problem?
