### ISSUE TITLE
Provider not defined

### ISSUE THREAD

**Issue by baptou60** [edgardmessias/glpi-singlesignon#75]
Hello,
We have implemented the SSO plugin and the connection test with Azure AD is working.
However when we try to connect, we get a message at connection "Provider not defined".
On the Azure AD side, the connection logs indicate a “success” status.

We have the same problem as described in this post: https://forum.glpi-project.org/viewtopic.php?pid=503521#p503521

Have you ever had this problem? Do you have an idea for a resolution? I think I'm not far away, but I can't get anywhere
Thank you.

**Glpi version** : 10.0.5

**Comment by JustAnotherRandomUsername** [comment]
https://github.com/edgardmessias/glpi-singlesignon/blob/master/inc/toolbox.class.php

string number 42
the "$id" returns an array

you can change original string
`$url .= "/provider/".$id;`

to something like this
`$url .= "/provider/".$id['id'];`

but it also brooks the "test" button :)

also this fix is not relevant because "auto adding external users" not works too
